# Generated by Django 5.0.6 on 2024-06-15 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
